### ISSUE TITLE
Create personas

### ISSUE THREAD

**Issue by AdamT-S** [MMadejsza/Architecture_and_Design-_--_Coursework#20]
Create 1 or 2 personas per person

**Comment by MMadejsza** [comment]
1st persona was created and added as a screenshot to md file. Check if you like this idea - I know that there may be an issue with common formatting. But just in case you will try adding your one - check after pasting the pic, if it has width "800"

**Comment by MMadejsza** [comment]
The soldier guy looks cool! :D

**Comment by MMadejsza** [comment]
@AdamT-S How many do we need? Ready for the review stage?

**Comment by unaisq1** [comment]
Personas are done

**Comment by AdamT-S** [comment]
Personas look good, no changes from what I can see
