### ISSUE TITLE
Create system interfaces

### ISSUE THREAD

**Issue by unaisq1** [MMadejsza/Architecture_and_Design-_--_Coursework#22]

**Comment by unaisq1** [comment]
Uploaded diagram to develop branch under Graphical Models in Documentation. Awaiting review

**Comment by AdamT-S** [comment]
There is a typo in the ICustomerMGT interface (it reads ICOstomerMGT), other than that I see no other issues.

**Comment by AdamT-S** [comment]
Graph looks good, no changes needed
