### ISSUE TITLE
Identify architectural concepts encompassing Simple Architecture principles and Outlining a component specification diagram for this system.

### ISSUE THREAD

**Issue by MMadejsza** [MMadejsza/Architecture_and_Design-_--_Coursework#6]

**Comment by AdamT-S** [comment]
I have reviewed the diagram, and made some changes. It needs to be reviewed again before it is approved.

**Comment by MMadejsza** [comment]
I think it's better now too. I would say approved at least for sprint 1. We may add some adjustments later on along with an enhanced understanding of the coursework and technologies.

**Comment by MMadejsza** [comment]
I would only remind you guys to work on the proper branch. So for now - to pull and merge accordingly with branches being ahead or behind

**Comment by MMadejsza** [comment]
Wrong version received - update issue

**Comment by MMadejsza** [comment]
Corrected
